Traceback (most recent call last):
  File "nodes/control.py", line 9, in <module>
    ml.messages['go']['id']
KeyError: 'go'
Traceback (most recent call last):
  File "nodes/control.py", line 9, in <module>
    ml.messages['go']['id']
KeyError: 'go'
Traceback (most recent call last):
  File "nodes/control.py", line 9, in <module>
    ml.messages['go']['id']
KeyError: 'go'
Traceback (most recent call last):
  File "nodes/control.py", line 9, in <module>
    ml.messages['go']['id']
KeyError: 'go'
Traceback (most recent call last):
  File "nodes/control.py", line 66, in <module>
    main()
  File "nodes/control.py", line 31, in main
    canvas.print_out("move %s"%msg_data)
NameError: global name 'msg_data' is not defined
