Traceback (most recent call last):
  File "nodes/control.py", line 30, in <module>
    main()
  File "nodes/control.py", line 24, in main
    if (msg_id == ml['get_engine_status'].id):
TypeError: 'classobj' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "nodes/control.py", line 30, in <module>
    main()
  File "nodes/control.py", line 24, in main
    if (msg_id == ml['get_engine_status'].id):
TypeError: 'classobj' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "nodes/control.py", line 30, in <module>
    main()
  File "nodes/control.py", line 24, in main
    if (msg_id == ml.messages['get_engine_status'].id):
TypeError: 'classobj' object has no attribute '__getitem__'
Traceback (most recent call last):
  File "nodes/control.py", line 30, in <module>
    main()
  File "nodes/control.py", line 24, in main
    if (msg_id == ml.messages['get_engine_status']['id']):
AttributeError: 'dict' object has no attribute 'id'
